apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: ssh-agent-location
  description: Links to additional entities in the ssh-agent repository.
  annotations:
    github.com/project-slug: Bandwidth/ssh-agent
spec:
  targets:
    - ./component.yaml
